#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run precommit
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
yarn run build
